export interface BlogPost {
  slug: string;
  title: string;
  excerpt: string;
  category: string;
  toolSlug: string;
  date: string;
  readTime: string;
  status: "published" | "draft";
  publishedDate: string;
  modifiedDate: string;
}

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: "phq-9-guide",
    title: "PHQ-9 Explained: How Clinicians Use This Depression Questionnaire (and What It Can't Tell You)",
    excerpt: "Learn what the PHQ-9 measures, how healthcare providers interpret scores, and why this widely-used screener is only a starting point — not a diagnosis.",
    category: "Tool Guide",
    toolSlug: "/phq-9-depression-test",
    date: "2025-01-15",
    readTime: "8 min read",
    status: "published",
    publishedDate: "2025-01-15",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "gad-7-guide",
    title: "GAD-7 Anxiety Scale: What It Measures and How Doctors Interpret Scores",
    excerpt: "A plain-language guide to the GAD-7, the world's most commonly used anxiety screener — what it catches, what it misses, and what to do with your results.",
    category: "Tool Guide",
    toolSlug: "/gad-7-anxiety-test",
    date: "2025-01-20",
    readTime: "7 min read",
    status: "published",
    publishedDate: "2025-01-20",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "audit-guide",
    title: "AUDIT Alcohol Screening Tool: How It Works and Why Clinicians Use It",
    excerpt: "Understanding the WHO's AUDIT alcohol screening questionnaire — its origins, how it's scored, and what your results mean in context.",
    category: "Tool Guide",
    toolSlug: "/audit-alcohol-test",
    date: "2025-01-25",
    readTime: "9 min read",
    status: "published",
    publishedDate: "2025-01-25",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "work-stress-vs-burnout",
    title: "Work Stress vs. Burnout: How to Tell the Difference (and What Online Quizzes Can't Tell You)",
    excerpt: "Am I burned out or just stressed? The WHO-defined signs of clinical burnout vs. normal work stress, why online self-checks have limits, and when to talk to a professional.",
    category: "Education",
    toolSlug: "/work-stress-check",
    date: "2025-02-01",
    readTime: "6 min read",
    status: "published",
    publishedDate: "2025-02-01",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "sleep-and-mood",
    title: "How Sleep Affects Your Mood (and Why Poor Sleep Makes Everything Harder)",
    excerpt: "The science behind the sleep-mood connection — why poor sleep worsens anxiety and depression, how to tell if sleep is affecting your mental health, and what to do about it.",
    category: "Education",
    toolSlug: "/sleep-and-mood-check",
    date: "2025-02-10",
    readTime: "7 min read",
    status: "published",
    publishedDate: "2025-02-10",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "seasonal-affective-disorder",
    title: "Seasonal Affective Disorder (SAD): Understanding Winter Depression and Light Therapy",
    excerpt: "What is seasonal affective disorder? Learn why it happens in winter, how light therapy works, why it differs from regular depression, and when to seek professional help.",
    category: "Education",
    toolSlug: "/phq-9-depression-test",
    date: "2025-02-21",
    readTime: "9 min read",
    status: "published",
    publishedDate: "2025-02-21",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "depression-screening-guide",
    title: "Depression Screening Guide: PHQ-9 Assessment, USPSTF Guidelines & Treatment Options",
    excerpt: "Complete guide to depression screening for adults. Learn how the PHQ-9 assessment works, understand USPSTF recommendations, and discover evidence-based treatment approaches.",
    category: "Education",
    toolSlug: "/phq-9-depression-test",
    date: "2025-03-01",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2025-03-01",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "anxiety-coping-strategies",
    title: "Evidence-Based Anxiety Coping Strategies: Clinical Guide to Managing Anxiety Symptoms",
    excerpt: "Learn clinically validated anxiety coping strategies backed by NIH research. Discover cognitive-behavioral techniques, mindfulness practices, and lifestyle changes.",
    category: "Education",
    toolSlug: "/gad-7-anxiety-test",
    date: "2025-03-10",
    readTime: "9 min read",
    status: "published",
    publishedDate: "2025-03-10",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "dast-10-guide",
    title: "Understanding the DAST-10: Scoring, Interpretation & What Your Results Mean",
    excerpt: "Learn how the DAST-10 drug screening is scored, what each severity level means, and how it compares to the CAGE-AID and AUDIT.",
    category: "Tool Guide",
    toolSlug: "/dast-10-drug-screening",
    date: "2026-03-05",
    readTime: "8 min read",
    status: "published",
    publishedDate: "2026-03-05",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "ptsd-screening-guide",
    title: "PTSD Screening: When and Why to Get Tested",
    excerpt: "Learn when to get screened for PTSD, how the PCL-5 and PC-PTSD-5 work, what different scores mean, and what treatment options are available.",
    category: "Education",
    toolSlug: "/pcl-5-ptsd-screening",
    date: "2026-03-05",
    readTime: "9 min read",
    status: "published",
    publishedDate: "2026-03-05",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "adult-adhd-signs",
    title: "Adult ADHD: Signs You Might Have Missed",
    excerpt: "Common signs of ADHD in adults, why it's underdiagnosed — especially in women — the three presentations, and how to get screened.",
    category: "Education",
    toolSlug: "/asrs-adhd-screening",
    date: "2026-03-05",
    readTime: "9 min read",
    status: "published",
    publishedDate: "2026-03-05",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "bipolar-vs-depression",
    title: "Bipolar Disorder vs Depression: Key Differences",
    excerpt: "Understand the key differences between bipolar disorder and depression, why misdiagnosis happens, and which screening tools can help.",
    category: "Education",
    toolSlug: "/mdq-bipolar-screening",
    date: "2026-03-05",
    readTime: "9 min read",
    status: "published",
    publishedDate: "2026-03-05",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "what-ocd-looks-like",
    title: "OCD Myths vs Reality: What OCD Really Looks Like",
    excerpt: "What OCD actually looks like beyond the stereotypes. Learn about subtypes, the anxiety cycle, ERP treatment, and the OCI-R screening tool.",
    category: "Education",
    toolSlug: "/oci-r-ocd-screening",
    date: "2026-03-05",
    readTime: "9 min read",
    status: "published",
    publishedDate: "2026-03-05",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "stages-of-change-recovery",
    title: "The Stages of Change in Addiction Recovery",
    excerpt: "Understand the 5 stages of change model for addiction recovery. Learn what helps at each stage and how relapse fits into the process.",
    category: "Education",
    toolSlug: "/readiness-to-change",
    date: "2026-03-05",
    readTime: "9 min read",
    status: "published",
    publishedDate: "2026-03-05",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "quit-drinking-timeline",
    title: "What Happens When You Stop Drinking: A Timeline",
    excerpt: "Hour-by-hour and week-by-week timeline of what happens to your body after quitting alcohol. Includes critical safety warnings about withdrawal.",
    category: "Education",
    toolSlug: "/health-recovery-timeline",
    date: "2026-03-05",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2026-03-05",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "eating-disorder-signs",
    title: "Understanding Eating Disorders: Types, Signs & Screening",
    excerpt: "Learn about eating disorder types, warning signs, who is at risk, and how the SCOFF screening tool works. Includes helpline resources.",
    category: "Education",
    toolSlug: "/scoff-eating-disorder-screening",
    date: "2026-03-05",
    readTime: "9 min read",
    status: "published",
    publishedDate: "2026-03-05",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "relapse-prevention-plan-guide",
    title: "How to Build a Relapse Prevention Plan",
    excerpt: "Step-by-step guide to building a relapse prevention plan. Learn the three stages of relapse, identify triggers, and create your coping toolkit.",
    category: "Recovery",
    toolSlug: "/relapse-prevention-plan",
    date: "2026-03-05",
    readTime: "9 min read",
    status: "published",
    publishedDate: "2026-03-05",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "cognitive-distortions-list",
    title: "Cognitive Distortions: 15 Thinking Errors That Fuel Anxiety",
    excerpt: "Learn about 15 common cognitive distortions, how they fuel anxiety and depression, and how CBT can help you reframe them with examples.",
    category: "Education",
    toolSlug: "/cognitive-distortion-identifier",
    date: "2026-03-05",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2026-03-05",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "ace-score-meaning",
    title: "ACE Scores: What Your Childhood Experiences Mean for Your Health",
    excerpt: "What your ACE score means, how adverse childhood experiences affect health, and why resilience matters more than the number.",
    category: "Education",
    toolSlug: "/ace-questionnaire",
    date: "2026-03-05",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2026-03-05",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "social-anxiety-vs-introversion",
    title: "Social Anxiety vs Introversion: Understanding the Difference",
    excerpt: "Is it introversion or social anxiety? Learn the key differences, symptoms, the SPIN screening tool, and when to seek professional help.",
    category: "Education",
    toolSlug: "/spin-social-anxiety-test",
    date: "2026-03-05",
    readTime: "8 min read",
    status: "published",
    publishedDate: "2026-03-05",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "loneliness-mental-health",
    title: "Loneliness Epidemic: Why It Matters for Your Mental Health",
    excerpt: "The loneliness epidemic is a public health crisis. Learn how chronic loneliness affects mental and physical health, and evidence-based strategies to help.",
    category: "Education",
    toolSlug: "/ucla-loneliness-scale",
    date: "2026-03-05",
    readTime: "9 min read",
    status: "published",
    publishedDate: "2026-03-05",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "dbt-skills-beginners",
    title: "DBT Skills for Everyday Life: A Beginner's Guide",
    excerpt: "Learn the 4 DBT skill modules — mindfulness, distress tolerance, emotion regulation, and interpersonal effectiveness — in plain language.",
    category: "Education",
    toolSlug: "/dbt-crisis-skills",
    date: "2026-03-05",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2026-03-05",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "helping-family-member-addiction",
    title: "How to Help a Family Member with Addiction",
    excerpt: "Practical guidance for families dealing with a loved one's addiction. Learn about boundaries, enabling, self-care, and support resources.",
    category: "Family Support",
    toolSlug: "/family-impact-assessment",
    date: "2026-03-05",
    readTime: "9 min read",
    status: "published",
    publishedDate: "2026-03-05",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "depression-vs-anxiety",
    title: "Depression vs. Anxiety: What's the Difference?",
    excerpt: "Depression and anxiety share symptoms but have key differences. Learn what distinguishes them, how they overlap, and how each is identified and treated.",
    category: "Education",
    toolSlug: "/phq-9-depression-test",
    date: "2026-03-10",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "what-does-phq-9-score-mean",
    title: "What Does Your PHQ-9 Score Mean?",
    excerpt: "PHQ-9 scores range from 0\u201327. Learn what each score range means, how severity is classified, and what to do next based on your results.",
    category: "Education",
    toolSlug: "/phq-9-depression-test",
    date: "2026-03-10",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "what-does-gad-7-score-mean",
    title: "What Does Your GAD-7 Score Mean?",
    excerpt: "GAD-7 scores range from 0\u201321. Learn what minimal, mild, moderate, and severe anxiety scores mean and when to seek professional support.",
    category: "Education",
    toolSlug: "/gad-7-anxiety-test",
    date: "2026-03-10",
    readTime: "9 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "what-does-audit-score-mean",
    title: "What Does Your AUDIT Score Mean?",
    excerpt: "AUDIT scores range from 0\u201340. Learn what each score zone means \u2014 from low risk to possible dependence \u2014 and what steps to take based on your results.",
    category: "Education",
    toolSlug: "/audit-alcohol-test",
    date: "2026-03-10",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "when-should-i-see-a-therapist",
    title: "When Should I See a Therapist? 10 Signs",
    excerpt: "Not sure if therapy is for you? These 10 signs suggest it may be time to talk to a mental health professional \u2014 and what to expect when you do.",
    category: "Education",
    toolSlug: "/phq-9-depression-test",
    date: "2026-03-10",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "what-is-phq-9-depression-screener",
    title: "What Is the PHQ-9? Complete Guide to the Depression Screener",
    excerpt: "The PHQ-9 is a 9-question validated depression screening tool. Learn how it works, what it measures, who developed it, and how to interpret results.",
    category: "Education",
    toolSlug: "/phq-9-depression-test",
    date: "2026-03-10",
    readTime: "11 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "how-to-talk-to-doctor-about-mental-health",
    title: "How to Talk to Your Doctor About Mental Health",
    excerpt: "Talking to a doctor about mental health can feel daunting. Here\u2019s exactly what to say, how to prepare, and what to expect \u2014 including how to use your screening results.",
    category: "Education",
    toolSlug: "/phq-9-depression-test",
    date: "2026-03-10",
    readTime: "9 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "phq-9-vs-gad-7",
    title: "PHQ-9 vs GAD-7: Which Should You Take?",
    excerpt: "The PHQ-9 screens for depression, the GAD-7 for anxiety. Learn how they differ, when to take each, and why taking both together is often most useful.",
    category: "Education",
    toolSlug: "/phq-9-depression-test",
    date: "2026-03-10",
    readTime: "9 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "what-is-alcohol-use-disorder",
    title: "What Is Alcohol Use Disorder (AUD)?",
    excerpt: "Alcohol use disorder is a medical condition involving loss of control over drinking despite negative consequences. Learn the symptoms, risk factors, and evidence-based treatments.",
    category: "Education",
    toolSlug: "/audit-alcohol-test",
    date: "2026-03-10",
    readTime: "12 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "what-is-generalized-anxiety-disorder",
    title: "What Is Generalized Anxiety Disorder (GAD)?",
    excerpt: "Generalized anxiety disorder is characterized by persistent, difficult-to-control worry about multiple areas of life. Learn the symptoms, causes, and treatments.",
    category: "Education",
    toolSlug: "/gad-7-anxiety-test",
    date: "2026-03-10",
    readTime: "11 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "what-does-asrs-score-mean",
    title: "What Does Your ASRS Score Mean?",
    excerpt: "The ASRS-v1.1 screens for adult ADHD using 6 questions. Learn what a positive screen means, how the scoring works, and what to do with your results.",
    category: "Education",
    toolSlug: "/asrs-adhd-screening",
    date: "2026-03-10",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "what-does-pcl-5-score-mean",
    title: "What Does Your PCL-5 Score Mean?",
    excerpt: "PCL-5 scores range from 0\u201380. Learn what each score threshold means, how PTSD severity is classified, and what to do after getting your results.",
    category: "Education",
    toolSlug: "/pcl-5-ptsd-screening",
    date: "2026-03-10",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "what-is-anxiety",
    title: "What Is Anxiety? Symptoms, Types, and Treatment",
    excerpt: "Anxiety is normal \u2014 but anxiety disorders are not just being worried. Learn the difference, how the main anxiety disorders are defined, and what evidence-based treatment looks like.",
    category: "Education",
    toolSlug: "/gad-7-anxiety-test",
    date: "2026-03-10",
    readTime: "14 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "how-to-find-a-therapist",
    title: "How to Find a Therapist: A Step-by-Step Guide",
    excerpt: "Finding a therapist is harder than it should be. Here\u2019s a practical, step-by-step guide for finding one that fits your needs, budget, and insurance \u2014 without the runaround.",
    category: "Education",
    toolSlug: "/phq-9-depression-test",
    date: "2026-03-10",
    readTime: "12 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "mental-health-and-sleep",
    title: "Mental Health and Sleep: How They Affect Each Other",
    excerpt: "Poor sleep worsens mental health, and mental health conditions disrupt sleep. Learn how this bidirectional relationship works and what you can do to break the cycle.",
    category: "Education",
    toolSlug: "/phq-9-depression-test",
    date: "2026-03-10",
    readTime: "13 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "what-is-bipolar-disorder",
    title: "What Is Bipolar Disorder? Types, Symptoms, and Treatment",
    excerpt: "Bipolar disorder is widely misunderstood and frequently misdiagnosed. Learn what it actually is, how bipolar I and II differ, and what evidence-based treatment looks like.",
    category: "Education",
    toolSlug: "/mdq-bipolar-screening",
    date: "2026-03-10",
    readTime: "14 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "what-is-adhd-in-adults",
    title: "What Is ADHD in Adults? Symptoms, Diagnosis, and Treatment",
    excerpt: "ADHD in adults often looks nothing like childhood ADHD. Learn the real symptoms of adult ADHD, why it\u2019s so often missed, and what effective treatment looks like.",
    category: "Education",
    toolSlug: "/asrs-adhd-screening",
    date: "2026-03-10",
    readTime: "12 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "what-does-pc-ptsd-5-score-mean",
    title: "What Does Your PC-PTSD-5 Score Mean?",
    excerpt: "PC-PTSD-5 scores range from 0\u20135. A score of 3 or higher is a positive screen for PTSD. Learn what your result means and when to follow up with the full PCL-5.",
    category: "Education",
    toolSlug: "/pc-ptsd-5-screening",
    date: "2026-03-10",
    readTime: "9 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "what-does-ace-score-mean",
    title: "What Does Your ACE Score Mean?",
    excerpt: "ACE scores range from 0\u201310. Learn what your Adverse Childhood Experiences score means, how childhood trauma affects adult health, and what to do with your results.",
    category: "Education",
    toolSlug: "/ace-questionnaire",
    date: "2026-03-10",
    readTime: "12 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "what-does-oci-r-score-mean",
    title: "What Does Your OCI-R Score Mean?",
    excerpt: "OCI-R scores range from 0\u201372 across six subscales. Learn what the total score and subscale scores mean, what the clinical cutoff is, and what to do with your results.",
    category: "Education",
    toolSlug: "/oci-r-ocd-screening",
    date: "2026-03-10",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "what-does-cage-aid-score-mean",
    title: "What Does Your CAGE-AID Score Mean?",
    excerpt: "CAGE-AID scores range from 0\u20134. A score of 2 or higher suggests a possible substance use problem. Learn what your result means and what steps to take next.",
    category: "Education",
    toolSlug: "/cage-aid-substance-abuse-screening",
    date: "2026-03-10",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "what-does-pss-score-mean",
    title: "What Does Your PSS Score Mean?",
    excerpt: "PSS-10 scores range from 0\u201340. Learn what your Perceived Stress Scale score means, what the score ranges indicate, and practical steps to take based on your results.",
    category: "Education",
    toolSlug: "/dass-21-depression-anxiety-stress",
    date: "2026-03-10",
    readTime: "11 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "what-does-rosenberg-self-esteem-score-mean",
    title: "What Does Your Rosenberg Self-Esteem Scale Score Mean?",
    excerpt: "Rosenberg Self-Esteem Scale scores range from 0\u201330. Learn what high and low scores mean, how self-esteem connects to mental health, and when to seek support.",
    category: "Education",
    toolSlug: "/rosenberg-self-esteem-scale",
    date: "2026-03-10",
    readTime: "12 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "what-is-ocd",
    title: "What Is OCD? Symptoms, Misconceptions, and Treatment",
    excerpt: "OCD is widely misunderstood. It is not about being neat or particular. Learn what obsessive-compulsive disorder actually is, how it works, and what effective treatment looks like.",
    category: "Education",
    toolSlug: "/oci-r-ocd-screening",
    date: "2026-03-10",
    readTime: "14 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "what-is-social-anxiety-disorder",
    title: "What Is Social Anxiety Disorder? Symptoms, Causes, and Treatment",
    excerpt: "Social anxiety is more than shyness. Learn what social anxiety disorder actually is, how it differs from introversion, and what evidence-based treatments work.",
    category: "Education",
    toolSlug: "/spin-social-anxiety-test",
    date: "2026-03-10",
    readTime: "16 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "what-are-substance-use-disorders",
    title: "What Are Substance Use Disorders? Signs, Diagnosis, and Treatment",
    excerpt: "Substance use disorder is a medical condition, not a moral failure. Learn what it is, how it\u2019s diagnosed, what the warning signs are, and what treatment looks like.",
    category: "Education",
    toolSlug: "/audit-alcohol-test",
    date: "2026-03-10",
    readTime: "18 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "mental-health-stigma",
    title: "Mental Health Stigma: What It Is, Why It Persists, and How to Fight It",
    excerpt: "Stigma is one of the biggest barriers to mental health care. Learn what mental health stigma is, where it comes from, how it causes harm, and what actually reduces it.",
    category: "Education",
    toolSlug: "/phq-9-depression-test",
    date: "2026-03-10",
    readTime: "14 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "how-to-support-someone-with-mental-health-condition",
    title: "How to Support Someone With a Mental Health Condition",
    excerpt: "Supporting someone with depression, anxiety, PTSD, or another mental health condition can be hard to get right. Here\u2019s what actually helps \u2014 and what to avoid.",
    category: "Education",
    toolSlug: "/phq-9-depression-test",
    date: "2026-03-10",
    readTime: "15 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "understanding-mental-health-screening-results",
    title: "Understanding Your Mental Health Screening Results",
    excerpt: "Took a mental health screening and not sure what to do next? This guide explains what screening results mean, what they don\u2019t mean, and your practical next steps.",
    category: "Education",
    toolSlug: "/phq-9-depression-test",
    date: "2026-03-10",
    readTime: "14 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "anxiety-vs-panic-attacks",
    title: "Anxiety vs. Panic Attacks: What\u2019s the Difference?",
    excerpt: "Anxiety and panic attacks feel different and require different responses. Learn how to tell them apart, what causes each, and what to do when they happen.",
    category: "Education",
    toolSlug: "/gad-7-anxiety-test",
    date: "2026-03-10",
    readTime: "14 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
];
