export interface BlogPost {
  slug: string;
  title: string;
  excerpt: string;
  category: string;
  toolSlug: string;
  date: string;
  readTime: string;
  status: "published" | "draft";
  publishedDate: string;
  modifiedDate: string;
}

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: "phq-9-guide",
    title: "PHQ-9 Explained: How Clinicians Use This Depression Questionnaire (and What It Can't Tell You)",
    excerpt: "Learn what the PHQ-9 measures, how healthcare providers interpret scores, and why this widely-used screener is only a starting point — not a diagnosis.",
    category: "Tool Guide",
    toolSlug: "/phq-9-depression-test",
    date: "2025-01-15",
    readTime: "8 min read",
    status: "published",
    publishedDate: "2025-01-15",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "gad-7-guide",
    title: "GAD-7 Anxiety Scale: What It Measures and How Doctors Interpret Scores",
    excerpt: "A plain-language guide to the GAD-7, the world's most commonly used anxiety screener — what it catches, what it misses, and what to do with your results.",
    category: "Tool Guide",
    toolSlug: "/gad-7-anxiety-test",
    date: "2025-01-20",
    readTime: "7 min read",
    status: "published",
    publishedDate: "2025-01-20",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "audit-guide",
    title: "AUDIT Alcohol Screening Tool: How It Works and Why Clinicians Use It",
    excerpt: "Understanding the WHO's AUDIT alcohol screening questionnaire — its origins, how it's scored, and what your results mean in context.",
    category: "Tool Guide",
    toolSlug: "/audit-alcohol-test",
    date: "2025-01-25",
    readTime: "9 min read",
    status: "published",
    publishedDate: "2025-01-25",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "work-stress-vs-burnout",
    title: "Work Stress vs. Burnout: How to Tell the Difference (and What Online Quizzes Can't Tell You)",
    excerpt: "Am I burned out or just stressed? The WHO-defined signs of clinical burnout vs. normal work stress, why online self-checks have limits, and when to talk to a professional.",
    category: "Education",
    toolSlug: "/work-stress-check",
    date: "2025-02-01",
    readTime: "6 min read",
    status: "published",
    publishedDate: "2025-02-01",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "sleep-and-mood",
    title: "How Sleep Affects Your Mood (and Why Poor Sleep Makes Everything Harder)",
    excerpt: "The science behind the sleep-mood connection — why poor sleep worsens anxiety and depression, how to tell if sleep is affecting your mental health, and what to do about it.",
    category: "Education",
    toolSlug: "/sleep-and-mood-check",
    date: "2025-02-10",
    readTime: "7 min read",
    status: "published",
    publishedDate: "2025-02-10",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "seasonal-affective-disorder",
    title: "Seasonal Affective Disorder (SAD): Understanding Winter Depression and Light Therapy",
    excerpt: "What is seasonal affective disorder? Learn why it happens in winter, how light therapy works, why it differs from regular depression, and when to seek professional help.",
    category: "Education",
    toolSlug: "/phq-9-depression-test",
    date: "2025-02-21",
    readTime: "9 min read",
    status: "published",
    publishedDate: "2025-02-21",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "depression-screening-guide",
    title: "Depression Screening Guide: PHQ-9 Assessment, USPSTF Guidelines & Treatment Options",
    excerpt: "Complete guide to depression screening for adults. Learn how the PHQ-9 assessment works, understand USPSTF recommendations, and discover evidence-based treatment approaches.",
    category: "Education",
    toolSlug: "/phq-9-depression-test",
    date: "2025-03-01",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2025-03-01",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "anxiety-coping-strategies",
    title: "Evidence-Based Anxiety Coping Strategies: Clinical Guide to Managing Anxiety Symptoms",
    excerpt: "Learn clinically validated anxiety coping strategies backed by NIH research. Discover cognitive-behavioral techniques, mindfulness practices, and lifestyle changes.",
    category: "Education",
    toolSlug: "/gad-7-anxiety-test",
    date: "2025-03-10",
    readTime: "9 min read",
    status: "published",
    publishedDate: "2025-03-10",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "dast-10-guide",
    title: "Understanding the DAST-10: Scoring, Interpretation & What Your Results Mean",
    excerpt: "Learn how the DAST-10 drug screening is scored, what each severity level means, and how it compares to the CAGE-AID and AUDIT.",
    category: "Tool Guide",
    toolSlug: "/dast-10-drug-screening",
    date: "2026-03-05",
    readTime: "8 min read",
    status: "published",
    publishedDate: "2026-03-05",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "ptsd-screening-guide",
    title: "PTSD Screening: When and Why to Get Tested",
    excerpt: "Learn when to get screened for PTSD, how the PCL-5 and PC-PTSD-5 work, what different scores mean, and what treatment options are available.",
    category: "Education",
    toolSlug: "/pcl-5-ptsd-screening",
    date: "2026-03-05",
    readTime: "9 min read",
    status: "published",
    publishedDate: "2026-03-05",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "adult-adhd-signs",
    title: "Adult ADHD: Signs You Might Have Missed",
    excerpt: "Common signs of ADHD in adults, why it's underdiagnosed — especially in women — the three presentations, and how to get screened.",
    category: "Education",
    toolSlug: "/asrs-adhd-screening",
    date: "2026-03-05",
    readTime: "9 min read",
    status: "published",
    publishedDate: "2026-03-05",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "bipolar-vs-depression",
    title: "Bipolar Disorder vs Depression: Key Differences",
    excerpt: "Understand the key differences between bipolar disorder and depression, why misdiagnosis happens, and which screening tools can help.",
    category: "Education",
    toolSlug: "/mdq-bipolar-screening",
    date: "2026-03-05",
    readTime: "9 min read",
    status: "published",
    publishedDate: "2026-03-05",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "what-ocd-looks-like",
    title: "OCD Myths vs Reality: What OCD Really Looks Like",
    excerpt: "What OCD actually looks like beyond the stereotypes. Learn about subtypes, the anxiety cycle, ERP treatment, and the OCI-R screening tool.",
    category: "Education",
    toolSlug: "/oci-r-ocd-screening",
    date: "2026-03-05",
    readTime: "9 min read",
    status: "published",
    publishedDate: "2026-03-05",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "stages-of-change-recovery",
    title: "The Stages of Change in Addiction Recovery",
    excerpt: "Understand the 5 stages of change model for addiction recovery. Learn what helps at each stage and how relapse fits into the process.",
    category: "Education",
    toolSlug: "/readiness-to-change",
    date: "2026-03-05",
    readTime: "9 min read",
    status: "published",
    publishedDate: "2026-03-05",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "quit-drinking-timeline",
    title: "What Happens When You Stop Drinking: A Timeline",
    excerpt: "Hour-by-hour and week-by-week timeline of what happens to your body after quitting alcohol. Includes critical safety warnings about withdrawal.",
    category: "Education",
    toolSlug: "/health-recovery-timeline",
    date: "2026-03-05",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2026-03-05",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "eating-disorder-signs",
    title: "Understanding Eating Disorders: Types, Signs & Screening",
    excerpt: "Learn about eating disorder types, warning signs, who is at risk, and how the SCOFF screening tool works. Includes helpline resources.",
    category: "Education",
    toolSlug: "/scoff-eating-disorder-screening",
    date: "2026-03-05",
    readTime: "9 min read",
    status: "published",
    publishedDate: "2026-03-05",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "relapse-prevention-plan-guide",
    title: "How to Build a Relapse Prevention Plan",
    excerpt: "Step-by-step guide to building a relapse prevention plan. Learn the three stages of relapse, identify triggers, and create your coping toolkit.",
    category: "Recovery",
    toolSlug: "/relapse-prevention-plan",
    date: "2026-03-05",
    readTime: "9 min read",
    status: "published",
    publishedDate: "2026-03-05",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "cognitive-distortions-list",
    title: "Cognitive Distortions: 15 Thinking Errors That Fuel Anxiety",
    excerpt: "Learn about 15 common cognitive distortions, how they fuel anxiety and depression, and how CBT can help you reframe them with examples.",
    category: "Education",
    toolSlug: "/cognitive-distortion-identifier",
    date: "2026-03-05",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2026-03-05",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "ace-score-meaning",
    title: "ACE Scores: What Your Childhood Experiences Mean for Your Health",
    excerpt: "What your ACE score means, how adverse childhood experiences affect health, and why resilience matters more than the number.",
    category: "Education",
    toolSlug: "/ace-questionnaire",
    date: "2026-03-05",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2026-03-05",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "social-anxiety-vs-introversion",
    title: "Social Anxiety vs Introversion: Understanding the Difference",
    excerpt: "Is it introversion or social anxiety? Learn the key differences, symptoms, the SPIN screening tool, and when to seek professional help.",
    category: "Education",
    toolSlug: "/spin-social-anxiety-test",
    date: "2026-03-05",
    readTime: "8 min read",
    status: "published",
    publishedDate: "2026-03-05",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "loneliness-mental-health",
    title: "Loneliness Epidemic: Why It Matters for Your Mental Health",
    excerpt: "The loneliness epidemic is a public health crisis. Learn how chronic loneliness affects mental and physical health, and evidence-based strategies to help.",
    category: "Education",
    toolSlug: "/ucla-loneliness-scale",
    date: "2026-03-05",
    readTime: "9 min read",
    status: "published",
    publishedDate: "2026-03-05",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "dbt-skills-beginners",
    title: "DBT Skills for Everyday Life: A Beginner's Guide",
    excerpt: "Learn the 4 DBT skill modules — mindfulness, distress tolerance, emotion regulation, and interpersonal effectiveness — in plain language.",
    category: "Education",
    toolSlug: "/dbt-crisis-skills",
    date: "2026-03-05",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2026-03-05",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "helping-family-member-addiction",
    title: "How to Help a Family Member with Addiction",
    excerpt: "Practical guidance for families dealing with a loved one's addiction. Learn about boundaries, enabling, self-care, and support resources.",
    category: "Family Support",
    toolSlug: "/family-impact-assessment",
    date: "2026-03-05",
    readTime: "9 min read",
    status: "published",
    publishedDate: "2026-03-05",
    modifiedDate: "2026-03-08",
  },
];
