export interface BlogPost {
  slug: string;
  title: string;
  excerpt: string;
  category: string;
  toolSlug: string;
  date: string;
  readTime: string;
  status: "published" | "draft";
  publishedDate: string;
  modifiedDate: string;
}

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: "phq-9-guide",
    title: "PHQ-9 Explained: How Clinicians Use This Depression Questionnaire (and What It Can't Tell You)",
    excerpt: "Learn what the PHQ-9 measures, how healthcare providers interpret scores, and why this widely-used screener is only a starting point — not a diagnosis.",
    category: "Tool Guide",
    toolSlug: "/phq-9-depression-test",
    date: "2025-01-15",
    readTime: "8 min read",
    status: "published",
    publishedDate: "2025-01-15",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "gad-7-guide",
    title: "GAD-7 Anxiety Scale: What It Measures and How Doctors Interpret Scores",
    excerpt: "A plain-language guide to the GAD-7, the world's most commonly used anxiety screener — what it catches, what it misses, and what to do with your results.",
    category: "Tool Guide",
    toolSlug: "/gad-7-anxiety-test",
    date: "2025-01-20",
    readTime: "7 min read",
    status: "published",
    publishedDate: "2025-01-20",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "audit-guide",
    title: "AUDIT Alcohol Screening Tool: How It Works and Why Clinicians Use It",
    excerpt: "Understanding the WHO's AUDIT alcohol screening questionnaire — its origins, how it's scored, and what your results mean in context.",
    category: "Tool Guide",
    toolSlug: "/audit-alcohol-test",
    date: "2025-01-25",
    readTime: "9 min read",
    status: "published",
    publishedDate: "2025-01-25",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "work-stress-vs-burnout",
    title: "Work Stress vs. Burnout: How to Tell the Difference (and What Online Quizzes Can't Tell You)",
    excerpt: "Am I burned out or just stressed? The WHO-defined signs of clinical burnout vs. normal work stress, why online self-checks have limits, and when to talk to a professional.",
    category: "Education",
    toolSlug: "/work-stress-check",
    date: "2025-02-01",
    readTime: "6 min read",
    status: "published",
    publishedDate: "2025-02-01",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "sleep-and-mood",
    title: "How Sleep Affects Your Mood (and Why Poor Sleep Makes Everything Harder)",
    excerpt: "The science behind the sleep-mood connection — why poor sleep worsens anxiety and depression, how to tell if sleep is affecting your mental health, and what to do about it.",
    category: "Education",
    toolSlug: "/sleep-and-mood-check",
    date: "2025-02-10",
    readTime: "7 min read",
    status: "published",
    publishedDate: "2025-02-10",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "seasonal-affective-disorder",
    title: "Seasonal Affective Disorder (SAD): Understanding Winter Depression and Light Therapy",
    excerpt: "What is seasonal affective disorder? Learn why it happens in winter, how light therapy works, why it differs from regular depression, and when to seek professional help.",
    category: "Education",
    toolSlug: "/phq-9-depression-test",
    date: "2025-02-21",
    readTime: "9 min read",
    status: "published",
    publishedDate: "2025-02-21",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "depression-screening-guide",
    title: "Depression Screening Guide: PHQ-9 Assessment, USPSTF Guidelines & Treatment Options",
    excerpt: "Complete guide to depression screening for adults. Learn how the PHQ-9 assessment works, understand USPSTF recommendations, and discover evidence-based treatment approaches.",
    category: "Education",
    toolSlug: "/phq-9-depression-test",
    date: "2025-03-01",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2025-03-01",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "anxiety-coping-strategies",
    title: "Evidence-Based Anxiety Coping Strategies: Clinical Guide to Managing Anxiety Symptoms",
    excerpt: "Learn clinically validated anxiety coping strategies backed by NIH research. Discover cognitive-behavioral techniques, mindfulness practices, and lifestyle changes.",
    category: "Education",
    toolSlug: "/gad-7-anxiety-test",
    date: "2025-03-10",
    readTime: "9 min read",
    status: "published",
    publishedDate: "2025-03-10",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "dast-10-guide",
    title: "Understanding the DAST-10: Scoring, Interpretation & What Your Results Mean",
    excerpt: "Learn how the DAST-10 drug screening is scored, what each severity level means, and how it compares to the CAGE-AID and AUDIT.",
    category: "Tool Guide",
    toolSlug: "/dast-10-drug-screening",
    date: "2026-03-05",
    readTime: "8 min read",
    status: "published",
    publishedDate: "2026-03-05",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "ptsd-screening-guide",
    title: "PTSD Screening: When and Why to Get Tested",
    excerpt: "Learn when to get screened for PTSD, how the PCL-5 and PC-PTSD-5 work, what different scores mean, and what treatment options are available.",
    category: "Education",
    toolSlug: "/pcl-5-ptsd-screening",
    date: "2026-03-05",
    readTime: "9 min read",
    status: "published",
    publishedDate: "2026-03-05",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "adult-adhd-signs",
    title: "Adult ADHD: Signs You Might Have Missed",
    excerpt: "Common signs of ADHD in adults, why it's underdiagnosed — especially in women — the three presentations, and how to get screened.",
    category: "Education",
    toolSlug: "/asrs-adhd-screening",
    date: "2026-03-05",
    readTime: "9 min read",
    status: "published",
    publishedDate: "2026-03-05",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "bipolar-vs-depression",
    title: "Bipolar Disorder vs Depression: Key Differences",
    excerpt: "Understand the key differences between bipolar disorder and depression, why misdiagnosis happens, and which screening tools can help.",
    category: "Education",
    toolSlug: "/mdq-bipolar-screening",
    date: "2026-03-05",
    readTime: "9 min read",
    status: "published",
    publishedDate: "2026-03-05",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "what-ocd-looks-like",
    title: "OCD Myths vs Reality: What OCD Really Looks Like",
    excerpt: "What OCD actually looks like beyond the stereotypes. Learn about subtypes, the anxiety cycle, ERP treatment, and the OCI-R screening tool.",
    category: "Education",
    toolSlug: "/oci-r-ocd-screening",
    date: "2026-03-05",
    readTime: "9 min read",
    status: "published",
    publishedDate: "2026-03-05",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "stages-of-change-recovery",
    title: "The Stages of Change in Addiction Recovery",
    excerpt: "Understand the 5 stages of change model for addiction recovery. Learn what helps at each stage and how relapse fits into the process.",
    category: "Education",
    toolSlug: "/readiness-to-change",
    date: "2026-03-05",
    readTime: "9 min read",
    status: "published",
    publishedDate: "2026-03-05",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "quit-drinking-timeline",
    title: "What Happens When You Stop Drinking: A Timeline",
    excerpt: "Hour-by-hour and week-by-week timeline of what happens to your body after quitting alcohol. Includes critical safety warnings about withdrawal.",
    category: "Education",
    toolSlug: "/health-recovery-timeline",
    date: "2026-03-05",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2026-03-05",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "eating-disorder-signs",
    title: "Understanding Eating Disorders: Types, Signs & Screening",
    excerpt: "Learn about eating disorder types, warning signs, who is at risk, and how the SCOFF screening tool works. Includes helpline resources.",
    category: "Education",
    toolSlug: "/scoff-eating-disorder-screening",
    date: "2026-03-05",
    readTime: "9 min read",
    status: "published",
    publishedDate: "2026-03-05",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "relapse-prevention-plan-guide",
    title: "How to Build a Relapse Prevention Plan",
    excerpt: "Step-by-step guide to building a relapse prevention plan. Learn the three stages of relapse, identify triggers, and create your coping toolkit.",
    category: "Recovery",
    toolSlug: "/relapse-prevention-plan",
    date: "2026-03-05",
    readTime: "9 min read",
    status: "published",
    publishedDate: "2026-03-05",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "cognitive-distortions-list",
    title: "Cognitive Distortions: 15 Thinking Errors That Fuel Anxiety",
    excerpt: "Learn about 15 common cognitive distortions, how they fuel anxiety and depression, and how CBT can help you reframe them with examples.",
    category: "Education",
    toolSlug: "/cognitive-distortion-identifier",
    date: "2026-03-05",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2026-03-05",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "ace-score-meaning",
    title: "ACE Scores: What Your Childhood Experiences Mean for Your Health",
    excerpt: "What your ACE score means, how adverse childhood experiences affect health, and why resilience matters more than the number.",
    category: "Education",
    toolSlug: "/ace-questionnaire",
    date: "2026-03-05",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2026-03-05",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "social-anxiety-vs-introversion",
    title: "Social Anxiety vs Introversion: Understanding the Difference",
    excerpt: "Is it introversion or social anxiety? Learn the key differences, symptoms, the SPIN screening tool, and when to seek professional help.",
    category: "Education",
    toolSlug: "/spin-social-anxiety-test",
    date: "2026-03-05",
    readTime: "8 min read",
    status: "published",
    publishedDate: "2026-03-05",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "loneliness-mental-health",
    title: "Loneliness Epidemic: Why It Matters for Your Mental Health",
    excerpt: "The loneliness epidemic is a public health crisis. Learn how chronic loneliness affects mental and physical health, and evidence-based strategies to help.",
    category: "Education",
    toolSlug: "/ucla-loneliness-scale",
    date: "2026-03-05",
    readTime: "9 min read",
    status: "published",
    publishedDate: "2026-03-05",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "dbt-skills-beginners",
    title: "DBT Skills for Everyday Life: A Beginner's Guide",
    excerpt: "Learn the 4 DBT skill modules — mindfulness, distress tolerance, emotion regulation, and interpersonal effectiveness — in plain language.",
    category: "Education",
    toolSlug: "/dbt-crisis-skills",
    date: "2026-03-05",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2026-03-05",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "helping-family-member-addiction",
    title: "How to Help a Family Member with Addiction",
    excerpt: "Practical guidance for families dealing with a loved one's addiction. Learn about boundaries, enabling, self-care, and support resources.",
    category: "Family Support",
    toolSlug: "/family-impact-assessment",
    date: "2026-03-05",
    readTime: "9 min read",
    status: "published",
    publishedDate: "2026-03-05",
    modifiedDate: "2026-03-08",
  },
  {
    slug: "depression-vs-anxiety",
    title: "Depression vs. Anxiety: What's the Difference?",
    excerpt: "Depression and anxiety share symptoms but have key differences. Learn what distinguishes them, how they overlap, and how each is identified and treated.",
    category: "Education",
    toolSlug: "/phq-9-depression-test",
    date: "2026-03-10",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "what-does-phq-9-score-mean",
    title: "What Does Your PHQ-9 Score Mean?",
    excerpt: "PHQ-9 scores range from 0\u201327. Learn what each score range means, how severity is classified, and what to do next based on your results.",
    category: "Education",
    toolSlug: "/phq-9-depression-test",
    date: "2026-03-10",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "what-does-gad-7-score-mean",
    title: "What Does Your GAD-7 Score Mean?",
    excerpt: "GAD-7 scores range from 0\u201321. Learn what minimal, mild, moderate, and severe anxiety scores mean and when to seek professional support.",
    category: "Education",
    toolSlug: "/gad-7-anxiety-test",
    date: "2026-03-10",
    readTime: "9 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "what-does-audit-score-mean",
    title: "What Does Your AUDIT Score Mean?",
    excerpt: "AUDIT scores range from 0\u201340. Learn what each score zone means \u2014 from low risk to possible dependence \u2014 and what steps to take based on your results.",
    category: "Education",
    toolSlug: "/audit-alcohol-test",
    date: "2026-03-10",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "when-should-i-see-a-therapist",
    title: "When Should I See a Therapist? 10 Signs",
    excerpt: "Not sure if therapy is for you? These 10 signs suggest it may be time to talk to a mental health professional \u2014 and what to expect when you do.",
    category: "Education",
    toolSlug: "/phq-9-depression-test",
    date: "2026-03-10",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "what-is-phq-9-depression-screener",
    title: "What Is the PHQ-9? Complete Guide to the Depression Screener",
    excerpt: "The PHQ-9 is a 9-question validated depression screening tool. Learn how it works, what it measures, who developed it, and how to interpret results.",
    category: "Education",
    toolSlug: "/phq-9-depression-test",
    date: "2026-03-10",
    readTime: "11 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "how-to-talk-to-doctor-about-mental-health",
    title: "How to Talk to Your Doctor About Mental Health",
    excerpt: "Talking to a doctor about mental health can feel daunting. Here\u2019s exactly what to say, how to prepare, and what to expect \u2014 including how to use your screening results.",
    category: "Education",
    toolSlug: "/phq-9-depression-test",
    date: "2026-03-10",
    readTime: "9 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "phq-9-vs-gad-7",
    title: "PHQ-9 vs GAD-7: Which Should You Take?",
    excerpt: "The PHQ-9 screens for depression, the GAD-7 for anxiety. Learn how they differ, when to take each, and why taking both together is often most useful.",
    category: "Education",
    toolSlug: "/phq-9-depression-test",
    date: "2026-03-10",
    readTime: "9 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "what-is-alcohol-use-disorder",
    title: "What Is Alcohol Use Disorder (AUD)?",
    excerpt: "Alcohol use disorder is a medical condition involving loss of control over drinking despite negative consequences. Learn the symptoms, risk factors, and evidence-based treatments.",
    category: "Education",
    toolSlug: "/audit-alcohol-test",
    date: "2026-03-10",
    readTime: "12 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "what-is-generalized-anxiety-disorder",
    title: "What Is Generalized Anxiety Disorder (GAD)?",
    excerpt: "Generalized anxiety disorder is characterized by persistent, difficult-to-control worry about multiple areas of life. Learn the symptoms, causes, and treatments.",
    category: "Education",
    toolSlug: "/gad-7-anxiety-test",
    date: "2026-03-10",
    readTime: "11 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "what-does-asrs-score-mean",
    title: "What Does Your ASRS Score Mean?",
    excerpt: "The ASRS-v1.1 screens for adult ADHD using 6 questions. Learn what a positive screen means, how the scoring works, and what to do with your results.",
    category: "Education",
    toolSlug: "/asrs-adhd-screening",
    date: "2026-03-10",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "what-does-pcl-5-score-mean",
    title: "What Does Your PCL-5 Score Mean?",
    excerpt: "PCL-5 scores range from 0\u201380. Learn what each score threshold means, how PTSD severity is classified, and what to do after getting your results.",
    category: "Education",
    toolSlug: "/pcl-5-ptsd-screening",
    date: "2026-03-10",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "what-is-anxiety",
    title: "What Is Anxiety? Symptoms, Types, and Treatment",
    excerpt: "Anxiety is normal \u2014 but anxiety disorders are not just being worried. Learn the difference, how the main anxiety disorders are defined, and what evidence-based treatment looks like.",
    category: "Education",
    toolSlug: "/gad-7-anxiety-test",
    date: "2026-03-10",
    readTime: "14 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "how-to-find-a-therapist",
    title: "How to Find a Therapist: A Step-by-Step Guide",
    excerpt: "Finding a therapist is harder than it should be. Here\u2019s a practical, step-by-step guide for finding one that fits your needs, budget, and insurance \u2014 without the runaround.",
    category: "Education",
    toolSlug: "/phq-9-depression-test",
    date: "2026-03-10",
    readTime: "12 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "mental-health-and-sleep",
    title: "Mental Health and Sleep: How They Affect Each Other",
    excerpt: "Poor sleep worsens mental health, and mental health conditions disrupt sleep. Learn how this bidirectional relationship works and what you can do to break the cycle.",
    category: "Education",
    toolSlug: "/phq-9-depression-test",
    date: "2026-03-10",
    readTime: "13 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "what-is-bipolar-disorder",
    title: "What Is Bipolar Disorder? Types, Symptoms, and Treatment",
    excerpt: "Bipolar disorder is widely misunderstood and frequently misdiagnosed. Learn what it actually is, how bipolar I and II differ, and what evidence-based treatment looks like.",
    category: "Education",
    toolSlug: "/mdq-bipolar-screening",
    date: "2026-03-10",
    readTime: "14 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "what-is-adhd-in-adults",
    title: "What Is ADHD in Adults? Symptoms, Diagnosis, and Treatment",
    excerpt: "ADHD in adults often looks nothing like childhood ADHD. Learn the real symptoms of adult ADHD, why it\u2019s so often missed, and what effective treatment looks like.",
    category: "Education",
    toolSlug: "/asrs-adhd-screening",
    date: "2026-03-10",
    readTime: "12 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "what-does-pc-ptsd-5-score-mean",
    title: "What Does Your PC-PTSD-5 Score Mean?",
    excerpt: "PC-PTSD-5 scores range from 0\u20135. A score of 3 or higher is a positive screen for PTSD. Learn what your result means and when to follow up with the full PCL-5.",
    category: "Education",
    toolSlug: "/pc-ptsd-5-screening",
    date: "2026-03-10",
    readTime: "9 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "what-does-ace-score-mean",
    title: "What Does Your ACE Score Mean?",
    excerpt: "ACE scores range from 0\u201310. Learn what your Adverse Childhood Experiences score means, how childhood trauma affects adult health, and what to do with your results.",
    category: "Education",
    toolSlug: "/ace-questionnaire",
    date: "2026-03-10",
    readTime: "12 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "what-does-oci-r-score-mean",
    title: "What Does Your OCI-R Score Mean?",
    excerpt: "OCI-R scores range from 0\u201372 across six subscales. Learn what the total score and subscale scores mean, what the clinical cutoff is, and what to do with your results.",
    category: "Education",
    toolSlug: "/oci-r-ocd-screening",
    date: "2026-03-10",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "what-does-cage-aid-score-mean",
    title: "What Does Your CAGE-AID Score Mean?",
    excerpt: "CAGE-AID scores range from 0\u20134. A score of 2 or higher suggests a possible substance use problem. Learn what your result means and what steps to take next.",
    category: "Education",
    toolSlug: "/cage-aid-substance-abuse-screening",
    date: "2026-03-10",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "what-does-pss-score-mean",
    title: "What Does Your PSS Score Mean?",
    excerpt: "PSS-10 scores range from 0\u201340. Learn what your Perceived Stress Scale score means, what the score ranges indicate, and practical steps to take based on your results.",
    category: "Education",
    toolSlug: "/dass-21-depression-anxiety-stress",
    date: "2026-03-10",
    readTime: "11 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "what-does-rosenberg-self-esteem-score-mean",
    title: "What Does Your Rosenberg Self-Esteem Scale Score Mean?",
    excerpt: "Rosenberg Self-Esteem Scale scores range from 0\u201330. Learn what high and low scores mean, how self-esteem connects to mental health, and when to seek support.",
    category: "Education",
    toolSlug: "/rosenberg-self-esteem-scale",
    date: "2026-03-10",
    readTime: "12 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "what-is-ocd",
    title: "What Is OCD? Symptoms, Misconceptions, and Treatment",
    excerpt: "OCD is widely misunderstood. It is not about being neat or particular. Learn what obsessive-compulsive disorder actually is, how it works, and what effective treatment looks like.",
    category: "Education",
    toolSlug: "/oci-r-ocd-screening",
    date: "2026-03-10",
    readTime: "14 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "what-is-social-anxiety-disorder",
    title: "What Is Social Anxiety Disorder? Symptoms, Causes, and Treatment",
    excerpt: "Social anxiety is more than shyness. Learn what social anxiety disorder actually is, how it differs from introversion, and what evidence-based treatments work.",
    category: "Education",
    toolSlug: "/spin-social-anxiety-test",
    date: "2026-03-10",
    readTime: "16 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "what-are-substance-use-disorders",
    title: "What Are Substance Use Disorders? Signs, Diagnosis, and Treatment",
    excerpt: "Substance use disorder is a medical condition, not a moral failure. Learn what it is, how it\u2019s diagnosed, what the warning signs are, and what treatment looks like.",
    category: "Education",
    toolSlug: "/audit-alcohol-test",
    date: "2026-03-10",
    readTime: "18 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "mental-health-stigma",
    title: "Mental Health Stigma: What It Is, Why It Persists, and How to Fight It",
    excerpt: "Stigma is one of the biggest barriers to mental health care. Learn what mental health stigma is, where it comes from, how it causes harm, and what actually reduces it.",
    category: "Education",
    toolSlug: "/phq-9-depression-test",
    date: "2026-03-10",
    readTime: "14 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "how-to-support-someone-with-mental-health-condition",
    title: "How to Support Someone With a Mental Health Condition",
    excerpt: "Supporting someone with depression, anxiety, PTSD, or another mental health condition can be hard to get right. Here\u2019s what actually helps \u2014 and what to avoid.",
    category: "Education",
    toolSlug: "/phq-9-depression-test",
    date: "2026-03-10",
    readTime: "15 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "understanding-mental-health-screening-results",
    title: "Understanding Your Mental Health Screening Results",
    excerpt: "Took a mental health screening and not sure what to do next? This guide explains what screening results mean, what they don\u2019t mean, and your practical next steps.",
    category: "Education",
    toolSlug: "/phq-9-depression-test",
    date: "2026-03-10",
    readTime: "14 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "postpartum-depression-symptoms-guide",
    title: "Postpartum Depression Symptoms: Signs, Screening, and When to Get Help",
    excerpt: "Postpartum depression affects 1 in 7 new mothers. Learn the signs, how PPD differs from baby blues, risk factors, and how a free screening can help you take the next step.",
    category: "Education",
    toolSlug: "/postpartum-depression-test",
    date: "2026-03-17",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2026-03-17",
    modifiedDate: "2026-03-17",
  },
  {
    slug: "burnout-symptoms-guide",
    title: "Burnout Symptoms: How to Recognize the Signs Before It Gets Worse",
    excerpt: "Learn the WHO ICD-11 definition of burnout, the three Maslach dimensions, physical and emotional warning signs, and how burnout differs from depression.",
    category: "Education",
    toolSlug: "/burnout-assessment-tool",
    date: "2026-03-17",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2026-03-17",
    modifiedDate: "2026-03-17",
  },
  {
    slug: "attachment-styles-guide",
    title: "Understanding Attachment Styles: How Early Bonds Shape Adult Relationships",
    excerpt: "Attachment styles affect how you connect in relationships. Learn the four styles \u2014 secure, anxious, avoidant, and disorganized \u2014 and how a self-assessment can help.",
    category: "Education",
    toolSlug: "/attachment-style-quiz",
    date: "2026-03-17",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2026-03-17",
    modifiedDate: "2026-03-17",
  },
  {
    slug: "autism-screening-adults-guide",
    title: "Autism Screening for Adults: Signs, Self-Assessment, and Next Steps",
    excerpt: "Many adults discover they may be autistic later in life. Learn the signs of autism in adults, how the AQ-10 screening works, and what to do next.",
    category: "Education",
    toolSlug: "/aq-10-autism-screening",
    date: "2026-03-17",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2026-03-17",
    modifiedDate: "2026-03-17",
  },
  {
    slug: "dass-21-score-guide",
    title: "DASS-21 Score Guide: Understanding Your Depression, Anxiety, and Stress Scores",
    excerpt: "DASS-21 scores range from 0\u201342 per subscale. Learn what your Depression, Anxiety, and Stress scores mean, how severity levels are classified, and what to do next.",
    category: "Education",
    toolSlug: "/dass-21-depression-anxiety-stress",
    date: "2026-03-17",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2026-03-17",
    modifiedDate: "2026-03-17",
  },
  {
    slug: "grief-stages-guide",
    title: "Understanding Grief: Stages, Symptoms, and When to Seek Help",
    excerpt: "Grief is universal but experienced uniquely. Learn about the stages of grief, prolonged grief disorder, physical and emotional symptoms, and when to seek professional support.",
    category: "Education",
    toolSlug: "/grief-assessment",
    date: "2026-03-17",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2026-03-17",
    modifiedDate: "2026-03-17",
  },
  {
    slug: "insomnia-test-guide",
    title: "Insomnia Screening: Signs, Self-Assessment, and the Athens Insomnia Scale",
    excerpt: "Chronic insomnia affects about 10% of adults. Learn the signs, how the Athens Insomnia Scale works as a validated self-assessment, and when to seek professional help.",
    category: "Education",
    toolSlug: "/athens-insomnia-scale",
    date: "2026-03-17",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2026-03-17",
    modifiedDate: "2026-03-17",
  },
  {
    slug: "compassion-fatigue-guide",
    title: "Compassion Fatigue: Signs, Prevention, and Recovery for Caregivers",
    excerpt: "Compassion fatigue is the emotional cost of caring for others in distress. Learn the warning signs, who is at risk, and evidence-based prevention strategies.",
    category: "Education",
    toolSlug: "/compassion-fatigue-test",
    date: "2026-03-17",
    readTime: "8 min read",
    status: "published",
    publishedDate: "2026-03-17",
    modifiedDate: "2026-03-17",
  },
  {
    slug: "standard-drinks-bac-guide",
    title: "Standard Drinks and BAC: What You Need to Know About Alcohol Measurement",
    excerpt: "Learn what a standard drink is (14 grams of pure alcohol), how BAC is calculated, common misconceptions about drink sizes, and NIAAA low-risk drinking guidelines.",
    category: "Education",
    toolSlug: "/standard-drinks-calculator",
    date: "2026-03-17",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2026-03-17",
    modifiedDate: "2026-03-17",
  },
  {
    slug: "anxiety-vs-panic-attacks",
    title: "Anxiety vs. Panic Attacks: What\u2019s the Difference?",
    excerpt: "Anxiety and panic attacks feel different and require different responses. Learn how to tell them apart, what causes each, and what to do when they happen.",
    category: "Education",
    toolSlug: "/gad-7-anxiety-test",
    date: "2026-03-10",
    readTime: "14 min read",
    status: "published",
    publishedDate: "2026-03-10",
    modifiedDate: "2026-03-10",
  },
  {
    slug: "bpd-symptoms-guide",
    title: "Understanding BPD: Symptoms, Screening, and Treatment",
    excerpt: "Borderline personality disorder is one of the most misunderstood mental health conditions. Learn the DSM-5 criteria, how to screen for BPD, and why recovery is possible.",
    category: "Education",
    toolSlug: "/msi-bpd-screening",
    date: "2026-03-17",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2026-03-17",
    modifiedDate: "2026-03-17",
  },
  {
    slug: "sobriety-calculator-guide",
    title: "Sobriety Calculator: Why Tracking Your Sober Days Matters",
    excerpt: "Tracking sobriety time reinforces recovery motivation. Learn why counting sober days helps, what milestones mean, and how to use a free sobriety calculator.",
    category: "Recovery",
    toolSlug: "/sobriety-calculator",
    date: "2026-03-17",
    readTime: "9 min read",
    status: "published",
    publishedDate: "2026-03-17",
    modifiedDate: "2026-03-17",
  },
  {
    slug: "withdrawal-symptoms-guide",
    title: "Withdrawal Symptoms: What to Expect and When to Seek Medical Help",
    excerpt: "Withdrawal symptoms vary by substance and can range from uncomfortable to life-threatening. Learn what to expect, typical timelines, and when medical supervision is essential.",
    category: "Recovery",
    toolSlug: "/withdrawal-timeline",
    date: "2026-03-17",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2026-03-17",
    modifiedDate: "2026-03-17",
  },
  {
    slug: "urge-surfing-guide",
    title: "Urge Surfing: How to Ride Out Cravings Without Giving In",
    excerpt: "Urge surfing is a mindfulness technique for cravings. Learn how it works, why cravings peak and pass, and how a guided timer helps.",
    category: "Education",
    toolSlug: "/urge-surfing-timer",
    date: "2026-03-17",
    readTime: "9 min read",
    status: "published",
    publishedDate: "2026-03-17",
    modifiedDate: "2026-03-17",
  },
  {
    slug: "cbt-thought-record-guide",
    title: "CBT Thought Records: How to Challenge Negative Thinking Patterns",
    excerpt: "A thought record is a core CBT tool for identifying and challenging negative thinking. Learn the 7-column method and how to use it.",
    category: "Education",
    toolSlug: "/cbt-thought-record",
    date: "2026-03-17",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2026-03-17",
    modifiedDate: "2026-03-17",
  },
  {
    slug: "values-clarification-guide",
    title: "Values Clarification: How Knowing What Matters Guides Better Decisions",
    excerpt: "Values clarification helps you identify what truly matters to you. Learn how it's used in ACT therapy, recovery, and life decision-making.",
    category: "Education",
    toolSlug: "/values-card-sort",
    date: "2026-03-17",
    readTime: "9 min read",
    status: "published",
    publishedDate: "2026-03-17",
    modifiedDate: "2026-03-17",
  },
  {
    slug: "safety-planning-guide",
    title: "Safety Planning: A Step-by-Step Guide to Creating Your Crisis Plan",
    excerpt: "A safety plan is a written list of coping strategies and resources for when you are in crisis. Learn the 6 steps of the Stanley-Brown model.",
    category: "Education",
    toolSlug: "/safety-plan",
    date: "2026-03-17",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2026-03-17",
    modifiedDate: "2026-03-17",
  },
  {
    slug: "money-saved-recovery-guide",
    title: "Money Saved in Recovery: How Sobriety Changes Your Finances",
    excerpt: "See how much money you save by not drinking or using. A recovery calculator shows the financial impact of sobriety.",
    category: "Recovery",
    toolSlug: "/money-saved-recovery-calculator",
    date: "2026-03-17",
    readTime: "9 min read",
    status: "published",
    publishedDate: "2026-03-17",
    modifiedDate: "2026-03-17",
  },
  {
    slug: "health-recovery-timeline-guide",
    title: "Health Recovery After Quitting: What Happens to Your Body",
    excerpt: "Your body starts healing within hours of your last drink or use. See the timeline of physical health improvements in recovery.",
    category: "Recovery",
    toolSlug: "/health-recovery-timeline",
    date: "2026-03-17",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2026-03-17",
    modifiedDate: "2026-03-17",
  },
  {
    slug: "treatment-cost-guide",
    title: "Addiction Treatment Costs: What to Expect and How to Pay",
    excerpt: "Treatment costs range from free to $30,000+. Learn the cost of detox, inpatient, outpatient, and how insurance, Medicaid, and sliding scale options work.",
    category: "Recovery",
    toolSlug: "/treatment-cost-estimator",
    date: "2026-03-17",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2026-03-17",
    modifiedDate: "2026-03-17",
  },
  {
    slug: "halt-checkin-guide",
    title: "HALT: The Recovery Check-In That Prevents Relapse",
    excerpt: "HALT stands for Hungry, Angry, Lonely, Tired \u2014 four vulnerability states that increase relapse risk. Learn how this simple check-in works.",
    category: "Recovery",
    toolSlug: "/halt-check-in",
    date: "2026-03-17",
    readTime: "9 min read",
    status: "published",
    publishedDate: "2026-03-17",
    modifiedDate: "2026-03-17",
  },
  {
    slug: "relapse-prevention-guide",
    title: "Relapse Prevention: The Three Stages and How to Intervene Early",
    excerpt: "Relapse is a process, not an event. Learn the three stages \u2014 emotional, mental, and physical \u2014 how to recognize warning signs early, and evidence-based strategies that work.",
    category: "Recovery",
    toolSlug: "/relapse-prevention-plan",
    date: "2026-03-17",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2026-03-17",
    modifiedDate: "2026-03-17",
  },
  {
    slug: "trigger-identification-guide",
    title: "Trigger Identification: How to Recognize and Manage Relapse Triggers",
    excerpt: "Triggers are people, places, emotions, or situations that increase the urge to use. Learn how to identify your personal triggers and develop specific coping responses.",
    category: "Recovery",
    toolSlug: "/trigger-identification-worksheet",
    date: "2026-03-17",
    readTime: "9 min read",
    status: "published",
    publishedDate: "2026-03-17",
    modifiedDate: "2026-03-17",
  },
  {
    slug: "coping-skills-guide",
    title: "Coping Skills for Recovery: Evidence-Based Techniques That Actually Work",
    excerpt: "Coping skills are the bridge between recognizing a trigger and responding without using. Learn evidence-based behavioral, cognitive, mindfulness, and social coping strategies.",
    category: "Recovery",
    toolSlug: "/coping-skills-randomizer",
    date: "2026-03-17",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2026-03-17",
    modifiedDate: "2026-03-17",
  },
  {
    slug: "daily-recovery-checkin-guide",
    title: "Daily Recovery Check-Ins: Why Structured Self-Reflection Supports Sobriety",
    excerpt: "Daily check-ins help you track mood, cravings, and gratitude in recovery. Learn why self-monitoring supports sobriety and how to build a sustainable check-in routine.",
    category: "Recovery",
    toolSlug: "/daily-recovery-check-in",
    date: "2026-03-17",
    readTime: "9 min read",
    status: "published",
    publishedDate: "2026-03-17",
    modifiedDate: "2026-03-17",
  },
  {
    slug: "family-impact-addiction-guide",
    title: "How Addiction Affects Families: Understanding the Ripple Effects",
    excerpt: "Addiction affects every family member. Learn about family roles, codependency patterns, impact on children, and how families can begin their own recovery process.",
    category: "Family Support",
    toolSlug: "/family-impact-assessment",
    date: "2026-03-17",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2026-03-17",
    modifiedDate: "2026-03-17",
  },
  {
    slug: "readiness-to-change-guide",
    title: "Readiness to Change: Assessing Where You Are in the Change Process",
    excerpt: "The Transtheoretical Model identifies five stages of change. Learn how to assess your readiness, what helps at each stage, and why readiness fluctuates.",
    category: "Recovery",
    toolSlug: "/readiness-to-change",
    date: "2026-03-17",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2026-03-17",
    modifiedDate: "2026-03-17",
  },
  {
    slug: "worry-time-guide",
    title: "Worry Time: How Scheduling Your Worries Reduces Anxiety",
    excerpt: "Worry time is a CBT technique where you schedule 15-30 minutes daily for focused worrying and postpone worries outside that window. Learn how it reduces anxiety by 35-50%.",
    category: "Education",
    toolSlug: "/worry-time-scheduler",
    date: "2026-03-17",
    readTime: "9 min read",
    status: "published",
    publishedDate: "2026-03-17",
    modifiedDate: "2026-03-17",
  },
  {
    slug: "box-breathing-guide",
    title: "Box Breathing: A Simple Technique for Anxiety, Stress, and Panic",
    excerpt: "Box breathing (4-4-4-4) activates your parasympathetic nervous system to reduce anxiety, stress, and panic. Learn the technique, the science, and when to use it.",
    category: "Education",
    toolSlug: "/box-breathing-exercise",
    date: "2026-03-17",
    readTime: "9 min read",
    status: "published",
    publishedDate: "2026-03-17",
    modifiedDate: "2026-03-17",
  },
  {
    slug: "grounding-techniques-guide",
    title: "Grounding Techniques: How the 5-4-3-2-1 Method Calms Anxiety and Dissociation",
    excerpt: "Grounding techniques like the 5-4-3-2-1 method redirect attention from distress to the present moment. Learn how they work for anxiety, dissociation, and PTSD.",
    category: "Education",
    toolSlug: "/five-senses-grounding",
    date: "2026-03-17",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2026-03-17",
    modifiedDate: "2026-03-17",
  },
  {
    slug: "dbt-crisis-skills-guide",
    title: "DBT Crisis Survival Skills: What to Do When You Can\u2019t Think Straight",
    excerpt: "DBT crisis survival skills like TIPP and ACCEPTS help you get through acute distress without making things worse. Learn the key techniques and how to use them.",
    category: "Education",
    toolSlug: "/dbt-crisis-skills",
    date: "2026-03-17",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2026-03-17",
    modifiedDate: "2026-03-17",
  },
  {
    slug: "burnout-healthcare-workers-guide",
    title: "Burnout in Healthcare Workers: Signs, Causes, and What Actually Helps",
    excerpt: "Over 50% of healthcare workers report burnout. Learn the unique risk factors, warning signs, moral injury, and evidence-based strategies for physicians, nurses, and clinical staff.",
    category: "Education",
    toolSlug: "/burnout-test-for-healthcare-workers",
    date: "2026-03-17",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2026-03-17",
    modifiedDate: "2026-03-17",
  },
  {
    slug: "burnout-nurses-guide",
    title: "Nurse Burnout: Why It Happens, How It Feels, and What to Do About It",
    excerpt: "Nursing burnout affects over 60% of nurses. Learn the unique stressors nurses face, warning signs, and evidence-based strategies for protecting your well-being.",
    category: "Education",
    toolSlug: "/burnout-test-for-nurses",
    date: "2026-03-17",
    readTime: "9 min read",
    status: "published",
    publishedDate: "2026-03-17",
    modifiedDate: "2026-03-17",
  },
  {
    slug: "burnout-teachers-guide",
    title: "Teacher Burnout: Signs, Causes, and Strategies for Educators",
    excerpt: "Over 55% of educators have considered leaving the profession. Learn the unique factors driving teacher burnout and evidence-based strategies for sustaining your career.",
    category: "Education",
    toolSlug: "/burnout-test-for-teachers",
    date: "2026-03-17",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2026-03-17",
    modifiedDate: "2026-03-17",
  },
  {
    slug: "burnout-parents-guide",
    title: "Parental Burnout: When the Demands of Parenting Become Overwhelming",
    excerpt: "Parental burnout is a distinct condition affecting 5\u201320% of parents. Learn the signs, risk factors, and why it does not mean you are a bad parent.",
    category: "Education",
    toolSlug: "/burnout-test-parents",
    date: "2026-03-17",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2026-03-17",
    modifiedDate: "2026-03-17",
  },
  {
    slug: "caregiver-burnout-guide",
    title: "Caregiver Burnout: Signs, Prevention, and Getting Help for Yourself",
    excerpt: "53 million Americans are unpaid caregivers. Learn the signs of caregiver burnout, why self-care is not selfish, and how to access respite care and support.",
    category: "Education",
    toolSlug: "/caregiver-burnout-assessment",
    date: "2026-03-17",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2026-03-17",
    modifiedDate: "2026-03-17",
  },
  {
    slug: "adhd-teens-guide",
    title: "ADHD in Teenagers: Signs, Challenges, and How to Get Help",
    excerpt: "ADHD affects about 9.8% of US children. In teens, symptoms shift to executive function deficits. Learn the signs, why girls are often missed, and how screening helps.",
    category: "Education",
    toolSlug: "/adhd-test-for-teens",
    date: "2026-03-17",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2026-03-17",
    modifiedDate: "2026-03-17",
  },
  {
    slug: "depression-teens-guide",
    title: "Depression in Teenagers: Signs Parents Should Know",
    excerpt: "About 20% of teens experience depression before adulthood. Learn the warning signs, how teen depression differs from adult depression, risk factors, and how a free screening can help.",
    category: "Education",
    toolSlug: "/depression-test-for-teens",
    date: "2026-03-17",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2026-03-17",
    modifiedDate: "2026-03-17",
  },
  {
    slug: "anxiety-teens-guide",
    title: "Anxiety in Teenagers: How to Recognize It and What Actually Helps",
    excerpt: "About 32% of teens have an anxiety disorder. Learn how anxiety presents in adolescents, the role of social media, evidence-based approaches, and how a free screening can help.",
    category: "Education",
    toolSlug: "/anxiety-test-for-teens",
    date: "2026-03-17",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2026-03-17",
    modifiedDate: "2026-03-17",
  },
  {
    slug: "ocd-teens-guide",
    title: "OCD in Teenagers: What It Looks Like and How to Get Help",
    excerpt: "OCD often first appears in adolescence. Learn the real symptoms beyond stereotypes, how ERP treatment works, what parents should know, and how a free screening can help.",
    category: "Education",
    toolSlug: "/ocd-test-teens",
    date: "2026-03-17",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2026-03-17",
    modifiedDate: "2026-03-17",
  },
  {
    slug: "drug-screening-teens-guide",
    title: "Substance Use Screening for Teens: What Parents and Adolescents Should Know",
    excerpt: "About 15% of high school students report illicit drug use. Learn about the CRAFFT screening, common teen substances, risk factors, and how to start a conversation.",
    category: "Education",
    toolSlug: "/drug-screening-teens",
    date: "2026-03-17",
    readTime: "10 min read",
    status: "published",
    publishedDate: "2026-03-17",
    modifiedDate: "2026-03-17",
  },
];
