import { MetadataRoute } from "next";
import { SITE_URL } from "@/lib/metadata";
import { BLOG_POSTS } from "@/lib/blog";

export default function sitemap(): MetadataRoute.Sitemap {
  const lastUpdated = "2026-03-08T00:00:00.000Z";

  const staticPages = [
    { url: SITE_URL, lastModified: lastUpdated, changeFrequency: "weekly" as const, priority: 1.0 },
    { url: `${SITE_URL}/phq-9-depression-test`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.9 },
    { url: `${SITE_URL}/ces-d-depression-scale`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/gad-7-anxiety-test`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.9 },
    { url: `${SITE_URL}/audit-alcohol-test`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.9 },
    { url: `${SITE_URL}/audit-c-alcohol-screen`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/dast-10-drug-screening`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.9 },
    { url: `${SITE_URL}/cage-aid-substance-abuse-screening`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/pcl-5-ptsd-screening`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.9 },
    { url: `${SITE_URL}/pc-ptsd-5-screening`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/asrs-adhd-screening`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/mdq-bipolar-screening`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/oci-r-ocd-screening`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/dass-21-depression-anxiety-stress`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.9 },
    { url: `${SITE_URL}/who-5-wellbeing-index`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/k6-distress-scale`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/scoff-eating-disorder-screening`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/aq-10-autism-screening`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/sobriety-calculator`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/money-saved-recovery-calculator`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/health-recovery-timeline`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/bac-calculator`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/standard-drinks-calculator`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/halt-check-in`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/withdrawal-timeline`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/treatment-cost-estimator`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/relapse-prevention-plan`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/urge-surfing-timer`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/readiness-to-change`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/trigger-identification-worksheet`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/coping-skills-randomizer`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/daily-recovery-check-in`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/family-impact-assessment`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/burnout-assessment-tool`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.9 },
    { url: `${SITE_URL}/work-stress-check`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/mental-load-calculator`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/sleep-and-mood-check`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/spin-social-anxiety-test`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/who-assist-substance-screening`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.9 },
    { url: `${SITE_URL}/crafft-substance-screening`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/ace-questionnaire`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/holmes-rahe-stress-inventory`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/rosenberg-self-esteem-scale`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/ucla-loneliness-scale`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/athens-insomnia-scale`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/brief-resilience-scale`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/box-breathing-exercise`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/five-senses-grounding`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/cognitive-distortion-identifier`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/safety-plan`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.9 },
    { url: `${SITE_URL}/cbt-thought-record`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/worry-time-scheduler`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/values-card-sort`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/dbt-crisis-skills`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    // Guides
    { url: `${SITE_URL}/how-to-talk-to-your-doctor-about-mental-health`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    // Score interpretation guides
    { url: `${SITE_URL}/phq-9-score-interpretation`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/gad-7-score-interpretation`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/audit-score-interpretation`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/dast-10-score-interpretation`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/pcl-5-score-interpretation`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/asrs-score-interpretation`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/mdq-score-interpretation`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/dass-21-score-interpretation`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/ace-score-interpretation`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/audit-c-score-interpretation`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    // Targeted demographic screening pages
    { url: `${SITE_URL}/depression-test-for-teens`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.7 },
    { url: `${SITE_URL}/anxiety-test-for-women`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.7 },
    { url: `${SITE_URL}/alcohol-screening-for-college-students`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.7 },
    { url: `${SITE_URL}/burnout-test-for-nurses`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.7 },
    { url: `${SITE_URL}/depression-screening-for-veterans`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.7 },
    { url: `${SITE_URL}/ptsd-test-veterans`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.7 },
    { url: `${SITE_URL}/adhd-test-adults`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.7 },
    { url: `${SITE_URL}/adhd-test-women`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.7 },
    { url: `${SITE_URL}/anxiety-test-for-teens`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.7 },
    { url: `${SITE_URL}/anxiety-test-for-men`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.7 },
    { url: `${SITE_URL}/depression-test-for-seniors`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.7 },
    { url: `${SITE_URL}/depression-test-for-new-moms`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.7 },
    { url: `${SITE_URL}/ocd-test-teens`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.7 },
    { url: `${SITE_URL}/burnout-test-for-teachers`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.7 },
    { url: `${SITE_URL}/burnout-test-for-healthcare-workers`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.7 },
    { url: `${SITE_URL}/stress-test-college-students`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.7 },
    { url: `${SITE_URL}/alcohol-screening-military`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.7 },
    { url: `${SITE_URL}/drug-screening-teens`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.7 },
    { url: `${SITE_URL}/substance-abuse-test-parents`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.7 },
    { url: `${SITE_URL}/bipolar-test-young-adults`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.7 },
    { url: `${SITE_URL}/social-anxiety-test-college`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.7 },
    { url: `${SITE_URL}/loneliness-test-seniors`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.7 },
    { url: `${SITE_URL}/ptsd-test-first-responders`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.7 },
    { url: `${SITE_URL}/burnout-test-parents`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.7 },
    { url: `${SITE_URL}/eating-disorder-test-athletes`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.7 },
    // Conversational / intent-based landing pages (low-competition keywords)
    { url: `${SITE_URL}/am-i-depressed-quiz`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/do-i-have-ptsd-quiz`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/am-i-an-alcoholic-quiz`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/caregiver-burnout-assessment`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/compassion-fatigue-test`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/postpartum-depression-test`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/grief-assessment`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/phq-4-anxiety-depression-screen`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/contact`, lastModified: "2026-03-03T00:00:00.000Z", changeFrequency: "monthly" as const, priority: 0.4 },
    { url: `${SITE_URL}/blog`, lastModified: lastUpdated, changeFrequency: "weekly" as const, priority: 0.7 },
    { url: `${SITE_URL}/crisis-resources`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.8 },
    { url: `${SITE_URL}/about`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.6 },
    { url: `${SITE_URL}/privacy`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.4 },
    { url: `${SITE_URL}/cookies`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.4 },
    { url: `${SITE_URL}/terms`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.4 },
    { url: `${SITE_URL}/accessibility`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.4 },
    { url: `${SITE_URL}/disclaimer`, lastModified: lastUpdated, changeFrequency: "monthly" as const, priority: 0.4 },
  ];

  const blogPages = BLOG_POSTS
    .filter((p) => p.status === "published")
    .map((p) => ({
      url: `${SITE_URL}/blog/${p.slug}`,
      lastModified: new Date(p.date).toISOString(),
      changeFrequency: "monthly" as const,
      priority: 0.7,
    }));

  return [...staticPages, ...blogPages];
}
