name: Code Security

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "23 8 * * 1"

permissions:
  contents: read

jobs:
  dependency-review:
    name: Dependency review
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294 # v5.0.0

  codeql:
    name: CodeQL
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      security-events: write
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: github/codeql-action/init@4187e74d05793876e9989daffde9c3e66b4acd07 # v3
        with:
          languages: javascript-typescript
      - uses: github/codeql-action/analyze@e4fba868fa4b1b91e1fdab776edc8cfbe6e9fb81 # v4.37.3
